version: "3"
services:
  app:
      container_name: crudmobileusers
      restart: always
      build: .
      ports:
          - "8081:8081"
      links:
          - mongo
  mongo:
      container_name: mymongodatabase
      image: mongo
      ports:  
          - "27018:27017"
